name: Build & test

on: [push, pull_request]

jobs:
  linux:
    uses: przemek83/common/.github/workflows/build-and-test-go.yml@main
    with:
      platform: ubuntu-latest

  windows:
    uses: przemek83/common/.github/workflows/build-and-test-go.yml@main
    with:
      platform: windows-latest
